import { useState } from "react";
import { Alert, StyleSheet, Text, TextInput, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "../src/api/client";
import type { Currency } from "../src/api/types";
import { formatMoney } from "../src/lib/format";
import { PrimaryButton, ScreenMessage } from "../src/ui/components";
import { ScrollableScreen } from "../src/ui/Screen";
import { colors, commonStyles, spacing, typography } from "../src/ui/theme";
export default function Budget(){const [currency,setCurrency]=useState<Currency>("UYU");const [amount,setAmount]=useState("");const client=useQueryClient();const query=useQuery({queryKey:["budget",currency],queryFn:()=>api.budget(currency)});const report=useQuery({queryKey:["report",new Date().toISOString().slice(0,7),currency],queryFn:()=>api.dashboard(new Date().toISOString().slice(0,7),currency)});const mutation=useMutation({mutationFn:()=>api.updateBudget(currency,amount.trim()||null),onSuccess:()=>{void client.invalidateQueries({queryKey:["budget"]});void client.invalidateQueries({queryKey:["report"]});},onError:e=>Alert.alert("No se pudo guardar",e instanceof ApiError?e.message:"Revisá el importe.")});if(query.isPending||report.isPending)return <ScreenMessage title="Cargando presupuesto"/>;if(query.isError||report.isError||!query.data||!report.data)return <ScreenMessage title="No se pudo cargar el presupuesto"/>;const current=query.data.amount??"0";const spent=Number(report.data.expenses);const limit=Number(current);return <ScrollableScreen style={commonStyles.page} contentContainerStyle={styles.content}><Text style={typography.title}>Presupuestos</Text><Text style={typography.muted}>Período mensual en {currency}.</Text><View style={styles.chips}>{(["UYU","USD","UI"] as Currency[]).map(value=><Text key={value} onPress={()=>setCurrency(value)} style={[styles.chip,currency===value&&styles.active]}>{value}</Text>)}</View><View style={commonStyles.card}><Text style={typography.heading}>Presupuesto mensual</Text><TextInput accessibilityLabel="Importe del presupuesto" style={commonStyles.input} keyboardType="decimal-pad" placeholder={current} value={amount} onChangeText={setAmount}/><PrimaryButton label={mutation.isPending?"Guardando…":"Guardar presupuesto"} disabled={mutation.isPending} onPress={()=>mutation.mutate()}/></View><View style={commonStyles.card}><Text style={typography.heading}>Resumen del mes</Text><Text style={styles.value}>Utilizado: {formatMoney(String(spent),currency)}</Text><Text style={styles.value}>Disponible: {formatMoney(String(limit-spent),currency)}</Text></View></ScrollableScreen>}
const styles=StyleSheet.create({content:{...commonStyles.content,paddingBottom:spacing.xxl},chips:{flexDirection:"row",gap:spacing.sm},chip:{borderColor:colors.border,borderRadius:999,borderWidth:1,padding:spacing.sm},active:{backgroundColor:colors.primarySoft,borderColor:colors.primary},value:{...typography.body,marginTop:spacing.md}});