import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "../src/api/client";
import type { Category } from "../src/api/types";
import { Icon, PrimaryButton, ScreenMessage } from "../src/ui/components";
import { colors, commonStyles, radii, spacing, typography } from "../src/ui/theme";

export default function Categories() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["categories"], queryFn: () => api.categories() });
  const [name, setName] = useState(""); const [kind, setKind] = useState<"income" | "expense">("expense"); const [editing, setEditing] = useState<Category | null>(null);
  const mutation = useMutation({ mutationFn: () => editing ? api.updateCategory(editing.id, { name: name.trim() }) : api.createCategory({ name: name.trim(), kind }), onSuccess: async () => { setName(""); setEditing(null); await client.invalidateQueries({ queryKey: ["categories"] }); }, onError: e => Alert.alert("No se pudo guardar", e instanceof ApiError ? e.message : "Revisá los datos.") });
  const toggle = useMutation({ mutationFn: (item: Category) => api.updateCategory(item.id, { is_active: !item.is_active }), onSuccess: () => client.invalidateQueries({ queryKey: ["categories"] }) });
  if (query.isPending) return <ScreenMessage title="Cargando categorías" />; if (query.isError || !query.data) return <ScreenMessage title="No se pudieron cargar las categorías" />;
  const group = (value: "income" | "expense") => query.data.filter(x => x.kind === value);
  return <ScrollView style={commonStyles.page} contentContainerStyle={styles.content}><Text style={typography.title}>Categorías</Text><Text style={typography.muted}>Organizá ingresos y gastos sin modificar movimientos históricos.</Text><View style={commonStyles.card}><Text style={typography.heading}>{editing ? "Editar categoría" : "Nueva categoría"}</Text><TextInput accessibilityLabel="Nombre" style={styles.input} placeholder="Nombre" value={name} onChangeText={setName} /><View style={styles.switches}>{(["expense", "income"] as const).map(value => <Pressable key={value} onPress={() => setKind(value)} style={[styles.chip, kind === value && styles.selected]}><Text>{value === "expense" ? "Gastos" : "Ingresos"}</Text></Pressable>)}</View><PrimaryButton label={mutation.isPending ? "Guardando…" : editing ? "Guardar" : "Crear categoría"} disabled={!name.trim() || mutation.isPending} onPress={() => mutation.mutate()} />{editing ? <Pressable onPress={() => { setEditing(null); setName(""); }}><Text style={styles.cancel}>Cancelar</Text></Pressable> : null}</View>{(["expense", "income"] as const).map(value => <View key={value}><Text style={typography.heading}>{value === "expense" ? "Gastos" : "Ingresos"}</Text>{group(value).map(item => <View style={styles.row} key={item.id}><Icon name={item.is_active ? "pricetag-outline" : "archive-outline"} color={item.is_active ? colors.primary : colors.muted} /><Text style={styles.flex}>{item.name}{item.parent_id ? " · Subcategoría" : ""}</Text><Pressable onPress={() => { setEditing(item); setName(item.name); setKind(item.kind === "income" ? "income" : "expense"); }}><Text style={styles.action}>Editar</Text></Pressable><Pressable onPress={() => toggle.mutate(item)}><Text style={styles.action}>{item.is_active ? "Archivar" : "Activar"}</Text></Pressable></View>)}</View>)}</ScrollView>;
}
const styles = StyleSheet.create({ content: { ...commonStyles.content, gap: spacing.md, paddingBottom: spacing.xxl }, input: { ...commonStyles.input, marginTop: spacing.md }, switches: { flexDirection: "row", gap: spacing.sm, marginVertical: spacing.md }, chip: { borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, padding: spacing.sm }, selected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, row: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radii.md, flexDirection: "row", gap: spacing.sm, marginTop: spacing.sm, padding: spacing.md }, flex: { flex: 1, ...typography.body }, action: { color: colors.primary, fontWeight: "800" }, cancel: { color: colors.muted, textAlign: "center", marginTop: spacing.sm } });