import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import { api } from "../src/api/client";
import type { Currency } from "../src/api/types";
import { formatMoney } from "../src/lib/format";
import { ScreenMessage } from "../src/ui/components";
import { colors, commonStyles, radii, spacing, typography } from "../src/ui/theme";

export default function Reports() {
  const [currency, setCurrency] = useState<Currency>("UYU"); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const report = useQuery({ queryKey: ["report", month, currency], queryFn: () => api.dashboard(month, currency) }); const history = useQuery({ queryKey: ["history", currency], queryFn: () => api.history(12, currency) });
  if (report.isPending || history.isPending) return <ScreenMessage title="Cargando reportes" />; if (report.isError || history.isError || !report.data || !history.data) return <ScreenMessage title="No se pudieron cargar los reportes" detail="Reintentá cuando el servidor esté disponible." />;
  const data = report.data; const moveMonth = (delta: number) => { const date = new Date(`${month}-15T12:00:00`); date.setMonth(date.getMonth() + delta); setMonth(date.toISOString().slice(0, 7)); };
  return <ScrollView style={commonStyles.page} contentContainerStyle={styles.content}><Text style={typography.title}>Reportes</Text><Text style={typography.muted}>Análisis calculado por MyFinance.</Text><View style={styles.chips}>{(["UYU", "USD", "UI"] as Currency[]).map(value => <Pressable key={value} onPress={() => setCurrency(value)} style={[styles.chip, currency === value && styles.active]}><Text>{value}</Text></Pressable>)}</View><View style={commonStyles.card}><View style={styles.month}><Pressable onPress={() => moveMonth(-1)}><Text style={styles.action}>‹</Text></Pressable><Text style={typography.heading}>{month}</Text><Pressable onPress={() => moveMonth(1)}><Text style={styles.action}>›</Text></Pressable></View><View style={styles.metrics}><Metric label="Ingresos" value={data.income} currency={currency} /><Metric label="Gastos" value={data.expenses} currency={currency} /><Metric label="Resultado" value={data.net} currency={currency} /></View></View><Text style={typography.heading}>Gastos por categoría</Text>{data.categories.length ? data.categories.map(item => <View style={styles.row} key={`${item.category_id}-${item.name}`}><Text style={styles.flex}>{item.name}</Text><Text style={styles.amount}>{formatMoney(item.amount, currency)}</Text></View>) : <Text style={typography.muted}>No hay gastos en este período.</Text>}<Text style={typography.heading}>Evolución histórica</Text>{history.data.months.map(item => <View style={styles.row} key={item.month}><Text style={styles.flex}>{item.month}</Text><Text style={styles.amount}>{formatMoney(item.net, currency)}</Text></View>)}</ScrollView>;
}
function Metric({ label, value, currency }: { label: string; value: string; currency: Currency }) { return <View><Text style={typography.label}>{label}</Text><Text style={styles.metric}>{formatMoney(value, currency)}</Text></View>; }
const styles = StyleSheet.create({ content: { ...commonStyles.content, paddingBottom: spacing.xxl }, chips: { flexDirection: "row", gap: spacing.sm }, chip: { borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, active: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, month: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, action: { color: colors.primary, fontSize: 28, fontWeight: "800", paddingHorizontal: spacing.md }, metrics: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg }, metric: { color: colors.ink, fontSize: 17, fontWeight: "800", marginTop: spacing.xs }, row: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radii.md, flexDirection: "row", marginTop: spacing.sm, padding: spacing.md }, flex: { ...typography.body, flex: 1 }, amount: { ...typography.body, fontWeight: "800" } });