import { useState } from "react";
import { Alert, StyleSheet, Text, TextInput } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "../../src/api/client";
import { formatMoney, localDateIso } from "../../src/lib/format";
import { PrimaryButton, ScreenMessage } from "../../src/ui/components";
import { commonStyles, spacing, typography } from "../../src/ui/theme";
import { ScrollableScreen } from "../../src/ui/Screen";
export default function Reconcile(){const {id}=useLocalSearchParams<{id:string}>();const accountId=Number(id);const client=useQueryClient();const account=useQuery({queryKey:["account",id],queryFn:()=>api.account(accountId)});const [actual,setActual]=useState("");const mutation=useMutation({mutationFn:()=>api.reconcileAccount(accountId,{actual_balance:actual.trim(),date:localDateIso(new Date()),note:"Conciliación desde Mobile"}),onSuccess:async result=>{await Promise.all([client.invalidateQueries({queryKey:["account",id]}),client.invalidateQueries({queryKey:["accounts"]}),client.invalidateQueries({queryKey:["dashboard"]}),client.invalidateQueries({queryKey:["report"]})]);Alert.alert(result.already_reconciled?"Sin cambios":"Saldo reconciliado",result.already_reconciled?"El saldo ya estaba conciliado.":"Se generó el ajuste según las reglas del backend.",[ {text:"Continuar",onPress:()=>router.back()}]);},onError:e=>Alert.alert("No se pudo reconciliar",e instanceof ApiError?e.message:"Revisá el saldo ingresado.")});if(account.isPending)return <ScreenMessage title="Cargando cuenta"/>;if(account.isError||!account.data)return <ScreenMessage title="No se pudo cargar la cuenta"/>;return <ScrollableScreen style={commonStyles.page} contentContainerStyle={styles.content}><Text style={typography.title}>Reconciliar saldo</Text><Text style={typography.muted}>Saldo actual MyFinance</Text><Text style={styles.balance}>{formatMoney(account.data.current_balance,account.data.currency)}</Text><Text style={typography.muted}>Saldo real</Text><TextInput accessibilityLabel="Saldo real" style={commonStyles.input} keyboardType="decimal-pad" value={actual} onChangeText={setActual} placeholder="0.00"/><Text style={typography.muted}>Se generará un ajuste de reconciliación; Mobile no modifica saldos directamente.</Text><PrimaryButton label={mutation.isPending?"Procesando…":"Reconciliar saldo"} disabled={!actual.trim()||mutation.isPending} onPress={()=>mutation.mutate()}/></ScrollableScreen>}
const styles=StyleSheet.create({content:{...commonStyles.content,paddingBottom:spacing.xxl},balance:{...typography.title,marginVertical:spacing.md}});